// import { v4 as uuidv4 } from 'uuid'

// export const Goals = {
//   goals: [
//     {
//       id: uuidv4(),
//       title: 'Exercise',
//       periodSpent: 0,
//       timeCompleted: 0,
//       tags: ['#important', '#doDaily'],
//     },
//     {
//       id: uuidv4(),
//       title: 'Study Code',
//       periodSpent: 0,
//       timeCompleted: 0,
//       tags: ['#important', '#doDaily'],
//     },
//     {
//       id: uuidv4(),
//       title: 'Travel to other country',
//       periodSpent: 0,
//       timeCompleted: 0,
//       tags: '',
//     },
//     {
//       id: uuidv4(),
//       title: 'Learn Klingon',
//       periodSpent: 0,
//       timeCompleted: 0,
//       tags: ['#important', '#doWeekly'],
//     },
//   ],
// }
